# This file was generated by GoReleaser. DO NOT EDIT.
cask "gogh" do
  version "5.0.0-alpha.12"

  on_macos do
    on_intel do
      sha256 "18e6525c0f05df06610be050a58fdc01f67677e4a8f0bb16701f9a7f3cc4a744"
      url "https://github.com/kyoh86/gogh/releases/download/v#{version}/gogh_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kyoh86/gogh"
    end
    on_arm do
      sha256 "20f0322c51eec5611e381636c3197558c05229de1d64f351c42896b73d5c01bb"
      url "https://github.com/kyoh86/gogh/releases/download/v#{version}/gogh_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kyoh86/gogh"
    end
  end

  on_linux do
    on_intel do
      sha256 "1dbe6acbe9935aa669aba16f1a8b022627584552f46d842ec907fc2ff9ac87bc"
      url "https://github.com/kyoh86/gogh/releases/download/v#{version}/gogh_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kyoh86/gogh"
    end
    on_arm do
      sha256 "a2801dea3056f7044309ee4e60f50e0bb3147f5c027a492e164541f66210ac4a"
      url "https://github.com/kyoh86/gogh/releases/download/v#{version}/gogh_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kyoh86/gogh"
    end
  end

  name "gogh"
  desc "GO GitHub project manager"
  homepage "https://github.com/kyoh86/gogh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gogh"

  # No zap stanza required

end
