# This file was generated by GoReleaser. DO NOT EDIT.
cask "nvim-plugin-triage" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "a7b7a4425dea862bbf9cde9321cb8c39395a8f93b73be52a33b93cfbd977aa94"
      url "https://github.com/kyoh86/nvim-plugin-triage/releases/download/v#{version}/nvim-plugin-triage_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kyoh86/nvim-plugin-triage"
    end
    on_arm do
      sha256 "cd7def83e965c0c6392d59dc9104fcabf47367661fa1fddb08297185dcc669c3"
      url "https://github.com/kyoh86/nvim-plugin-triage/releases/download/v#{version}/nvim-plugin-triage_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kyoh86/nvim-plugin-triage"
    end
  end

  on_linux do
    on_intel do
      sha256 "78b37b607357c39ba43438cd68e60356e1eae8bf53e38e87b4be8a3eb3c7f8a2"
      url "https://github.com/kyoh86/nvim-plugin-triage/releases/download/v#{version}/nvim-plugin-triage_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kyoh86/nvim-plugin-triage"
    end
    on_arm do
      sha256 "1f0398f682c4972e5702a3aedf937635db37fbfe29f14fe76cbb5ae2c325d4ff"
      url "https://github.com/kyoh86/nvim-plugin-triage/releases/download/v#{version}/nvim-plugin-triage_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kyoh86/nvim-plugin-triage"
    end
  end

  name "nvim-plugin-triage"
  desc "Static triage for Neovim plugin repositories"
  homepage "https://github.com/kyoh86/nvim-plugin-triage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nvim-plugin-triage"

  # No zap stanza required

end
