# This file was generated by GoReleaser. DO NOT EDIT.
cask "nvim-plugin-triage" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "80b128965dadd6b6a804c67366576dfa8d4a1c919277de02ee476d875595995e"
      url "https://github.com/kyoh86/nvim-plugin-triage/releases/download/v#{version}/nvim-plugin-triage_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kyoh86/nvim-plugin-triage"
    end
    on_arm do
      sha256 "a9d45212db999f7cacf7cf20ec905a971a49db92c45bd5ff230a95ba9fc32273"
      url "https://github.com/kyoh86/nvim-plugin-triage/releases/download/v#{version}/nvim-plugin-triage_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kyoh86/nvim-plugin-triage"
    end
  end

  on_linux do
    on_intel do
      sha256 "65f596e61585b84311f996101f9d591b3d851e2e2006675d6ea3065db1fa1c60"
      url "https://github.com/kyoh86/nvim-plugin-triage/releases/download/v#{version}/nvim-plugin-triage_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kyoh86/nvim-plugin-triage"
    end
    on_arm do
      sha256 "8dda9466820bfb877d797493df64942decad72012b0521e8c747d201489fa12e"
      url "https://github.com/kyoh86/nvim-plugin-triage/releases/download/v#{version}/nvim-plugin-triage_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kyoh86/nvim-plugin-triage"
    end
  end

  name "nvim-plugin-triage"
  desc "Static triage for Neovim plugin repositories"
  homepage "https://github.com/kyoh86/nvim-plugin-triage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nvim-plugin-triage"

  # No zap stanza required

end
