# This file was generated by GoReleaser. DO NOT EDIT.
cask "nvim-plugin-triage" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "a17a2e0f0491bbf60d97be8f1d2b4852c2dcb0a9a7c2f00fca64d3e278253cad"
      url "https://github.com/kyoh86/nvim-plugin-triage/releases/download/v#{version}/nvim-plugin-triage_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kyoh86/nvim-plugin-triage"
    end
    on_arm do
      sha256 "b13c3b046da41305bedabe5b8b4e268eb36edbc4636965be265ebaa7f6aebf2d"
      url "https://github.com/kyoh86/nvim-plugin-triage/releases/download/v#{version}/nvim-plugin-triage_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kyoh86/nvim-plugin-triage"
    end
  end

  on_linux do
    on_intel do
      sha256 "ac22876292ed40897fe73b533dc7e416d3f441f0e902f334ea93cc4060a63477"
      url "https://github.com/kyoh86/nvim-plugin-triage/releases/download/v#{version}/nvim-plugin-triage_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kyoh86/nvim-plugin-triage"
    end
    on_arm do
      sha256 "6b7917bd4343b30867e695f61b3ec47c6649b27703fc21161dc2c1bf38f4718b"
      url "https://github.com/kyoh86/nvim-plugin-triage/releases/download/v#{version}/nvim-plugin-triage_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kyoh86/nvim-plugin-triage"
    end
  end

  name "nvim-plugin-triage"
  desc "Static triage for Neovim plugin repositories"
  homepage "https://github.com/kyoh86/nvim-plugin-triage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nvim-plugin-triage"

  # No zap stanza required

end
