# This file was generated by GoReleaser. DO NOT EDIT.
class Csv2xlsx < Formula
  desc ""
  homepage "https://github.com/kyoh86/csv2xlsx"
  version "0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kyoh86/csv2xlsx/releases/download/v0/csv2xlsx_0_darwin_amd64.tar.gz"
    sha256 "d7c63496c79e17b2bc488510a4e2522ea579389265e71e6c3fc2cff7147373e8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/csv2xlsx/releases/download/v0/csv2xlsx_0_linux_amd64.tar.gz"
      sha256 "7eed4d5f40fc6be8e2d63f4b007e369ade3b83bf50fb1d22d6729ae0d9cec4d1"
    end
  end

  def install
    bin.install "csv2xlsx"
    man1.install "csv2xlsx.1"
  end
end
