# This file was generated by GoReleaser. DO NOT EDIT.
class Docbase < Formula
  desc "A CLI tool to make the docbase more convenience!"
  homepage "https://github.com/kyoh86/docbase"
  url "https://github.com/kyoh86/docbase/releases/download/v0.0.2/docbase_0.0.2_darwin_amd64.tar.gz"
  version "0.0.2"
  sha256 "5ceca22229d41ba840b999871ca260dbadf09877ae8eefd3cff440347eae17aa"

  def install
    bin.install "docbase"
    man1.install "docbase.1"
  end
end
