# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitBranches < Formula
  desc "Show each branch, upstream, author in git repository"
  homepage "https://github.com/kyoh86/git-branches"
  version "0.0.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/git-branches/releases/download/v0.0.16/git-branches_0.0.16_darwin_amd64.tar.gz"
      sha256 "123a8de97f6b2a7bea9750c55455e9919b4bbb0142edeffac5d592a8074fd094"

      def install
        bin.install "git-branches"
        man1.install Dir.glob('git-branches*.1')
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyoh86/git-branches/releases/download/v0.0.16/git-branches_0.0.16_darwin_arm64.tar.gz"
      sha256 "f4179f5e593a1487f48a8871999944559de0502bc2c388f2ab21ef04a87a0c97"

      def install
        bin.install "git-branches"
        man1.install Dir.glob('git-branches*.1')
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/git-branches/releases/download/v0.0.16/git-branches_0.0.16_linux_amd64.tar.gz"
      sha256 "c6c099ec7500e058cb4d8e50f444febe4147ce97485f6c4e37239ea3902b71e3"

      def install
        bin.install "git-branches"
        man1.install Dir.glob('git-branches*.1')
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyoh86/git-branches/releases/download/v0.0.16/git-branches_0.0.16_linux_arm64.tar.gz"
      sha256 "fc64113821caa8f98de5926eeb6bfaf224903f222b640e76c3734583d93a5ab0"

      def install
        bin.install "git-branches"
        man1.install Dir.glob('git-branches*.1')
      end
    end
  end
end
