# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitBranches < Formula
  desc "Show each branch, upstream, author in git repository"
  homepage "https://github.com/kyoh86/git-branches"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kyoh86/git-branches/releases/download/v0.1.0/git-branches_0.1.0_darwin_amd64.tar.gz"
      sha256 "cca2eae4510fd00ac73782380526504cf1a58bd42c2c67dd0204b074ae9be580"

      def install
        bin.install "git-branches"
        man1.install Dir.glob('git-branches*.1')
      end
    end
    on_arm do
      url "https://github.com/kyoh86/git-branches/releases/download/v0.1.0/git-branches_0.1.0_darwin_arm64.tar.gz"
      sha256 "a00e425ecf66ff43458cb16e8eb387f916f354c24d446b6a24fdc777a7d71da6"

      def install
        bin.install "git-branches"
        man1.install Dir.glob('git-branches*.1')
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyoh86/git-branches/releases/download/v0.1.0/git-branches_0.1.0_linux_amd64.tar.gz"
        sha256 "0b624910c541385859bb4a8a2a1221b50cdb87c43079aa696e4fb11bc41e4943"

        def install
          bin.install "git-branches"
          man1.install Dir.glob('git-branches*.1')
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyoh86/git-branches/releases/download/v0.1.0/git-branches_0.1.0_linux_arm64.tar.gz"
        sha256 "5843ef2ccbbc0fa1b2d88afe5d4953ec1948f997efb406ca0a0c9aac7f294383"

        def install
          bin.install "git-branches"
          man1.install Dir.glob('git-branches*.1')
        end
      end
    end
  end
end
