# This file was generated by GoReleaser. DO NOT EDIT.
class GitVertag < Formula
  desc "A tool to manage version-tag with the semantic versioning specification."
  homepage "https://github.com/kyoh86/git-vertag"
  version "2.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kyoh86/git-vertag/releases/download/v2.0.2/git-vertag_2.0.2_darwin_amd64.tar.gz"
    sha256 "b18ca5de0e195b86409255398f4cb77a3cf188874f58da0b94ea6376785ea3fb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/git-vertag/releases/download/v2.0.2/git-vertag_2.0.2_linux_amd64.tar.gz"
      sha256 "2af2e5a960986e02c024d7e92541e629fef922c1aad4d151a3ceb13031984238"
    end
  end

  def install
    bin.install "git-vertag"
    man1.install "git-vertag.1"
  end
end
