# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitStatuses < Formula
  desc "Finds local git repositories and show statuses of them"
  homepage "https://github.com/kyoh86/git-statuses"
  version "1.1.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/kyoh86/git-statuses/releases/download/v1.1.2/git-statuses_1.1.2_darwin_amd64.tar.gz"
    sha256 "b1eb0127d2149a2f8b59161322e3cb0f565a4f3cbd29a7d6c595196a157d61a5"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/kyoh86/git-statuses/releases/download/v1.1.2/git-statuses_1.1.2_darwin_arm64.tar.gz"
    sha256 "63fa075db6f9876f310e6ef2e30e59a9bfa5cbe2b5475ea1e06b136f0d218646"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kyoh86/git-statuses/releases/download/v1.1.2/git-statuses_1.1.2_linux_amd64.tar.gz"
    sha256 "66ac553945a2ae912c0b291adbc0c8b1f90d13dfe01ea816aaa32b2f8fed8849"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/kyoh86/git-statuses/releases/download/v1.1.2/git-statuses_1.1.2_linux_armv6.tar.gz"
    sha256 "4436c8c19816cf4bbe4c94358cd4d7c82884cded27a2f36f9a8d230e131ebb2d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/kyoh86/git-statuses/releases/download/v1.1.2/git-statuses_1.1.2_linux_arm64.tar.gz"
    sha256 "d97ad80e9da228e0686701b34aca7e3e4448851cd4de34c9da360aa94b7c41d2"
  end

  def install
    bin.install "git-statuses"
    man1.install Dir.glob('git-statuses*.1')
  end
end
