# This file was generated by GoReleaser. DO NOT EDIT.
class GitBranches < Formula
  desc "Show each branch, upstream, author in git repository"
  homepage "https://github.com/kyoh86/git-branches"
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kyoh86/git-branches/releases/download/v0.0.5/git-branches_0.0.5_darwin_amd64.tar.gz"
    sha256 "ec825bb8f89a6499bbc4aceb451c46c18d7c72943ff8347d1a4fbe318bf4bf3a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/git-branches/releases/download/v0.0.5/git-branches_0.0.5_linux_amd64.tar.gz"
      sha256 "400ed3836b7915ea5af6c3ac77dc021ce4d5a923d82ab9c676cca364796efbf2"
    end
  end

  def install
    bin.install "git-branches"
    man1.install "git-branches.1"
  end
end
