# This file was generated by GoReleaser. DO NOT EDIT.
class GitVertag < Formula
  desc "A tool to manage version-tag with the semantic versioning specification."
  homepage "https://github.com/kyoh86/git-vertag"
  version "1.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kyoh86/git-vertag/releases/download/v1.2.0/git-vertag_1.2.0_darwin_amd64.tar.gz"
    sha256 "87b21141c087ac5ec61ed798e478ad3568d42f01bf7f830ba6597e39d69a67ab"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/git-vertag/releases/download/v1.2.0/git-vertag_1.2.0_linux_amd64.tar.gz"
      sha256 "21070f3148d71240920f6d2085151d8b86c0e342679981bc703f7694510d14a9"
    end
  end

  def install
    bin.install "git-vertag"
    man1.install "git-vertag.1"
  end
end
