# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitVertag < Formula
  desc "A tool to manage version-tag with the semantic versioning specification."
  homepage "https://github.com/kyoh86/git-vertag"
  version "2.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kyoh86/git-vertag/releases/download/v2.1.0/git-vertag_2.1.0_darwin_amd64.tar.gz"
      sha256 "5e45f432072d28f80009de7f8a28149f2a89edddf9d33c37c14a69956b1c1c63"

      def install
        bin.install "git-vertag"
        man1.install Dir.glob('git-vertag*.1')
      end
    end
    on_arm do
      url "https://github.com/kyoh86/git-vertag/releases/download/v2.1.0/git-vertag_2.1.0_darwin_arm64.tar.gz"
      sha256 "aa369bcc9be7fde553574577cae5e504024f14b8d54272ebc22581b96e7d2dd9"

      def install
        bin.install "git-vertag"
        man1.install Dir.glob('git-vertag*.1')
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyoh86/git-vertag/releases/download/v2.1.0/git-vertag_2.1.0_linux_amd64.tar.gz"
        sha256 "1076e743775436e4e550bbdd42fae89560f2fba750badcf05ed0673cbf82fb17"

        def install
          bin.install "git-vertag"
          man1.install Dir.glob('git-vertag*.1')
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyoh86/git-vertag/releases/download/v2.1.0/git-vertag_2.1.0_linux_arm64.tar.gz"
        sha256 "ff9613f27c32f5f068962bc9901f93758fb3504c42d86559715b1d5cd7b2d729"

        def install
          bin.install "git-vertag"
          man1.install Dir.glob('git-vertag*.1')
        end
      end
    end
  end
end
