# This file was generated by GoReleaser. DO NOT EDIT.
class GitPrompt < Formula
  desc "Show prompt strings for tmux, vim and zsh"
  homepage "https://github.com/kyoh86/git-prompt"
  version "0.0.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kyoh86/git-prompt/releases/download/v0.0.8/git-prompt_0.0.8_darwin_amd64.tar.gz"
    sha256 "21b3fcc78e3683d2e2bfab1b1a2085ce139f2e6bd38a914749dcbf80571455c6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/git-prompt/releases/download/v0.0.8/git-prompt_0.0.8_linux_amd64.tar.gz"
      sha256 "132107e5ea8c05c8d0798d83847b82620526ff48e3893aad371b8594f8209985"
    end
  end

  def install
    bin.install "git-prompt"
    man1.install "git-prompt.1"
  end
end
