# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gogh < Formula
  desc "GO GitHub project manager"
  homepage "https://github.com/kyoh86/gogh"
  version "4.0.1-alpha.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/gogh/releases/download/v4.0.1-alpha.17/gogh_4.0.1-alpha.17_darwin_amd64.tar.gz"
      sha256 "ef9091a998a93a746db921297732568e92fb91784cb4aa4976424d9fb420bdad"

      def install
        bin.install "gogh"
        man1.install Dir.glob('gogh*.1')
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyoh86/gogh/releases/download/v4.0.1-alpha.17/gogh_4.0.1-alpha.17_darwin_arm64.tar.gz"
      sha256 "29b522e21a0497836bf3dbbd2df0ffb302d8bb37adb9634782d8cf8e6de6c5ea"

      def install
        bin.install "gogh"
        man1.install Dir.glob('gogh*.1')
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kyoh86/gogh/releases/download/v4.0.1-alpha.17/gogh_4.0.1-alpha.17_linux_amd64.tar.gz"
      sha256 "d816b6615eaf9fe37fba36ac790513432a8a69db4da02c330d0ecc422364427e"
      def install
        bin.install "gogh"
        man1.install Dir.glob('gogh*.1')
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kyoh86/gogh/releases/download/v4.0.1-alpha.17/gogh_4.0.1-alpha.17_linux_arm64.tar.gz"
      sha256 "b7b427ad1aed275f69b69a4cc8ba51fd1bd7ab28a830a6f2f90905a314be1ff1"
      def install
        bin.install "gogh"
        man1.install Dir.glob('gogh*.1')
      end
    end
  end
end
