# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gogh < Formula
  desc "GO GitHub project manager"
  homepage "https://github.com/kyoh86/gogh"
  version "2.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/gogh/releases/download/v2.4.1/gogh_2.4.1_darwin_amd64.tar.gz"
      sha256 "d7f207053c67ff16b5836635a2e0c8012d3028d16b4061501d0379f4f8babd3f"

      def install
        bin.install "gogh"
        man1.install Dir.glob('gogh*.1')
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyoh86/gogh/releases/download/v2.4.1/gogh_2.4.1_darwin_arm64.tar.gz"
      sha256 "ab869c795812e5f6405a11b3b82f934355b35fdc56e81ffaebda350fdd4641c5"

      def install
        bin.install "gogh"
        man1.install Dir.glob('gogh*.1')
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/gogh/releases/download/v2.4.1/gogh_2.4.1_linux_amd64.tar.gz"
      sha256 "53faa4b6075b5eddd7ef46beed156b3a343fbe617d0eb599558bb389274f634f"

      def install
        bin.install "gogh"
        man1.install Dir.glob('gogh*.1')
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyoh86/gogh/releases/download/v2.4.1/gogh_2.4.1_linux_arm64.tar.gz"
      sha256 "797c79cd13dbe4557e62ee99b7a0dc119fdaca28bf56dba0480c8d39b6573147"

      def install
        bin.install "gogh"
        man1.install Dir.glob('gogh*.1')
      end
    end
  end
end
