# This file was generated by GoReleaser. DO NOT EDIT.
class Gordon < Formula
  desc "GO Released binaries DOwNloader"
  homepage "https://github.com/kyoh86/gordon"
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kyoh86/gordon/releases/download/v0.0.5/gordon_0.0.5_darwin_amd64.tar.gz"
    sha256 "784b99a8d4bfe62207059f5e56ddc300b811736ec5ee185445e6924ab10ab72f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/gordon/releases/download/v0.0.5/gordon_0.0.5_linux_amd64.tar.gz"
      sha256 "09f309e1c69ba463bc2bb86b41e52620224115e5f90713f1b5378c283f811fed"
    end
  end

  def install
    bin.install "gordon"
    man1.install "gordon.1"
  end
end
