# This file was generated by GoReleaser. DO NOT EDIT.
class Gordon < Formula
  desc "GO Released binaries DOwNloader"
  homepage "https://github.com/kyoh86/gordon"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kyoh86/gordon/releases/download/v0.0.1/gordon_0.0.1_darwin_amd64.tar.gz"
    sha256 "cc9fa27d40ffbdc9ae4f5638b15debbdd47bf273fa812a215d3d0d8991ed15ce"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/gordon/releases/download/v0.0.1/gordon_0.0.1_linux_amd64.tar.gz"
      sha256 "a9b0cf6d7ed76dc58162f7faaac73db1cd0557fec727e0700bd40e4e0df51571"
    end
  end

  def install
    bin.install "gordon"
    man1.install "gordon.1"
  end
end
