# This file was generated by GoReleaser. DO NOT EDIT.
class Looppointer < Formula
  desc "An analyzer that checks for pointers to enclosing loop variables."
  homepage "https://github.com/kyoh86/looppointer"
  version "0.1.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kyoh86/looppointer/releases/download/v0.1.6/looppointer_0.1.6_darwin_amd64.tar.gz"
    sha256 "444e82b203c1f9a183afa993a8a5f1942fd202fdf32f686b0ca0dc22443980a7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/looppointer/releases/download/v0.1.6/looppointer_0.1.6_linux_amd64.tar.gz"
      sha256 "66d573098c088a9d60acff42c094cff9f59818360dfaf2a80009c74840df9a2c"
    end
  end

  def install
    bin.install "looppointer"
  end
end
