# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Looppointer < Formula
  desc "An analyzer that checks for pointers to enclosing loop variables."
  homepage "https://github.com/kyoh86/looppointer"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/looppointer/releases/download/v0.2.0/looppointer_0.2.0_darwin_amd64.tar.gz"
      sha256 "fc265e5203a2b4ab33fc9a36684e91e9831c0c55f482940c782cb8dea0329e1e"

      def install
        bin.install "looppointer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyoh86/looppointer/releases/download/v0.2.0/looppointer_0.2.0_darwin_arm64.tar.gz"
      sha256 "789c1fce4ac4a6055e2f6d61eacb67241c2e9aaeb74f7a7af25ef19862787b70"

      def install
        bin.install "looppointer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyoh86/looppointer/releases/download/v0.2.0/looppointer_0.2.0_linux_arm64.tar.gz"
      sha256 "07b5d855c14c64d82291922d087c66e4d24b0bb9bdb5e38950a3562dbf7e0197"

      def install
        bin.install "looppointer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/looppointer/releases/download/v0.2.0/looppointer_0.2.0_linux_amd64.tar.gz"
      sha256 "78834e9476c9e4e8ae8fadfdfef08cbc03bfdeedf9fd88b44b4d4215d7d1c1f6"

      def install
        bin.install "looppointer"
      end
    end
  end
end
