# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Looppointer < Formula
  desc "An analyzer that checks for pointers to enclosing loop variables."
  homepage "https://github.com/kyoh86/looppointer"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kyoh86/looppointer/releases/download/v0.1.10/looppointer_0.1.10_darwin_arm64.tar.gz"
      sha256 "f193d961f9a281c31fa14e814fd259012dc9b58abbf4ba00d6f702b239df342a"

      def install
        bin.install "looppointer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/looppointer/releases/download/v0.1.10/looppointer_0.1.10_darwin_amd64.tar.gz"
      sha256 "26e39556613443591dad9f6dc87ad1aff62fee45a2e64f848ffb737be0abf8f0"

      def install
        bin.install "looppointer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyoh86/looppointer/releases/download/v0.1.10/looppointer_0.1.10_linux_arm64.tar.gz"
      sha256 "08ef3e435a69b48e2f868d290e6551dac890f2831939ba0ca96331a7fee1df84"

      def install
        bin.install "looppointer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/looppointer/releases/download/v0.1.10/looppointer_0.1.10_linux_amd64.tar.gz"
      sha256 "1550ef09dac80bcb0925d1b4bf25c3316c838c2827482417c969144c0732360b"

      def install
        bin.install "looppointer"
      end
    end
  end
end
