# This file was generated by GoReleaser. DO NOT EDIT.
class Notifail < Formula
  desc "Notify failure over OS notification drivers"
  homepage "https://github.com/kyoh86/notifail"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kyoh86/notifail/releases/download/v0.0.1/notifail_0.0.1_darwin_amd64.tar.gz"
    sha256 "d2d7cc21e004a90a6ac8643f966cfe730c69d2c1f0a363e04c701e524b3e90a1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/notifail/releases/download/v0.0.1/notifail_0.0.1_linux_amd64.tar.gz"
      sha256 "bdba506e78539734d81bfdfa6f0cbf4d068a380a91938718fb3b0f7beb206fb3"
    end
  end

  def install
    bin.install "notifail"
    man1.install "notifail.1"
  end
end
