# This file was generated by GoReleaser. DO NOT EDIT.
class Notifail < Formula
  desc "Notify failure over OS notification drivers"
  homepage "https://github.com/kyoh86/notifail"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kyoh86/notifail/releases/download/v0.0.1/notifail_0.0.1_darwin_amd64.tar.gz"
    sha256 "35701a3260f2d1738ef8ede52b90716f821a5a7f470b3308c118d4e0a6a0805a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/notifail/releases/download/v0.0.1/notifail_0.0.1_linux_amd64.tar.gz"
      sha256 "29f8136811f3aebe5ddff02b553c497d938db86064ef8984d0fa1c901787e403"
    end
  end

  def install
    bin.install "notifail"
    man1.install "notifail.1"
  end
end
