# This file was generated by GoReleaser. DO NOT EDIT.
class PyenvUpgrade < Formula
  desc "Upgrade all pyenv-envs"
  homepage "https://github.com/kyoh86/pyenv-upgrade"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kyoh86/pyenv-upgrade/releases/download/v0.0.3/pyenv-upgrade_0.0.3_darwin_amd64.tar.gz"
    sha256 "1c876e74e01211ffe43980d4ecb3af415849d53163e3273bc37a4eb3b27a6f45"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/pyenv-upgrade/releases/download/v0.0.3/pyenv-upgrade_0.0.3_linux_amd64.tar.gz"
      sha256 "9a29e4641613ae235ba1565bd7632ef2d292d0d3134a9c9e65c891640e8a9a36"
    end
  end

  def install
    bin.install "pyenv-upgrade"
    man1.install "pyenv-upgrade.1"
  end
end
