# This file was generated by GoReleaser. DO NOT EDIT.
class PyenvUpgrade < Formula
  desc "Upgrade all pyenv-envs"
  homepage "https://github.com/kyoh86/pyenv-upgrade"
  url "https://github.com/kyoh86/pyenv-upgrade/releases/download/v0.0.1/pyenv-upgrade_0.0.1_darwin_amd64.tar.gz"
  version "0.0.1"
  sha256 "a06b5063f96a8de1a8f24e5a5d6c96c9757d06fd6a4a65fe198fb111e7dc9c4d"

  def install
    bin.install "pyenv-upgrade"
    man1.install "pyenv-upgrade.1"
  end
end
