# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PyenvUpgrade < Formula
  desc "Upgrade all pyenv-envs"
  homepage "https://github.com/kyoh86/pyenv-upgrade"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kyoh86/pyenv-upgrade/releases/download/v0.0.4/pyenv-upgrade_0.0.4_darwin_arm64.tar.gz"
      sha256 "64d9e2faa25da7553c7f64375cc3370ac5212d657d2412c5a2eb8bf5197dd1f5"

      def install
        bin.install "pyenv-upgrade"
        man1.install Dir.glob('pyenv-upgrade*.1')
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/pyenv-upgrade/releases/download/v0.0.4/pyenv-upgrade_0.0.4_darwin_amd64.tar.gz"
      sha256 "3d69a1e01f8fa9b9ae00d9af17fb6774e0c88a6eb40ea70769c13a13abc8b3d0"

      def install
        bin.install "pyenv-upgrade"
        man1.install Dir.glob('pyenv-upgrade*.1')
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/pyenv-upgrade/releases/download/v0.0.4/pyenv-upgrade_0.0.4_linux_amd64.tar.gz"
      sha256 "d6d09c4a51e046457020e6d4ee05dd7077c2727a85b34563c7dd479e115d2c1b"

      def install
        bin.install "pyenv-upgrade"
        man1.install Dir.glob('pyenv-upgrade*.1')
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyoh86/pyenv-upgrade/releases/download/v0.0.4/pyenv-upgrade_0.0.4_linux_arm64.tar.gz"
      sha256 "f5861d17b0f28195bf999ee28bc87c7f5d978e5dd16660368fa7dc0baadf73f9"

      def install
        bin.install "pyenv-upgrade"
        man1.install Dir.glob('pyenv-upgrade*.1')
      end
    end
  end
end
