# This file was generated by GoReleaser. DO NOT EDIT.
class Richgo < Formula
  desc "Checks for unpinned variables in go programs."
  homepage "https://github.com/kyoh86/richgo"
  url "https://github.com/kyoh86/richgo/releases/download/v0.3.1/richgo_0.3.1_darwin_amd64.tar.gz"
  version "0.3.1"
  sha256 "12a084921d3f533b7696456df71025a05110b42b8cfe3c303189d0aca05f9144"

  def install
    bin.install "richgo"
  end
end
