# This file was generated by GoReleaser. DO NOT EDIT.
class Richgo < Formula
  desc "Rich-Go will enrich `go test` outputs with text decorations"
  homepage "https://github.com/kyoh86/richgo"
  version "0.3.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kyoh86/richgo/releases/download/v0.3.6/richgo_0.3.6_darwin_amd64.tar.gz"
    sha256 "e4a2601055042c74c6e4dd1e24f49e60781e5a8cf4b301406871b115608998c5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kyoh86/richgo/releases/download/v0.3.6/richgo_0.3.6_linux_amd64.tar.gz"
    sha256 "a73b808daf645aa0aafb335a959646c3e28c73118c97cb94ee07864669ea2cac"
  end

  def install
    bin.install "richgo"
  end
end
