# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Richgo < Formula
  desc "Rich-Go will enrich `go test` outputs with text decorations"
  homepage "https://github.com/kyoh86/richgo"
  version "0.3.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/richgo/releases/download/v0.3.11/richgo_0.3.11_darwin_amd64.tar.gz"
      sha256 "0eaf65234da229bc6899251b167d4e58c2a39230b48a39f7cd8cf5bc3275230e"

      def install
        bin.install "richgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyoh86/richgo/releases/download/v0.3.11/richgo_0.3.11_darwin_arm64.tar.gz"
      sha256 "47964a2b31b288de184ab932e652377a7ca926ca5578d41d7f0b00b7eb2dbe5d"

      def install
        bin.install "richgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/richgo/releases/download/v0.3.11/richgo_0.3.11_linux_amd64.tar.gz"
      sha256 "a263f8587152549705994d1cd032159bf461630e42ea793cd997674f14972acd"

      def install
        bin.install "richgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyoh86/richgo/releases/download/v0.3.11/richgo_0.3.11_linux_arm64.tar.gz"
      sha256 "acaf953560785b9adb477551bd6d030296d8986a8ef3f096ad21ac5f620982e8"

      def install
        bin.install "richgo"
      end
    end
  end
end
