# This file was generated by GoReleaser. DO NOT EDIT.
class Scopelint < Formula
  desc "scopelint checks for unpinned variables in go programs"
  homepage "https://github.com/kyoh86/scopelint"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kyoh86/scopelint/releases/download/v0.1.3/scopelint_0.1.3_darwin_amd64.tar.gz"
    sha256 "755f1dd027a117e8cf400e6e034a1afc6761050f76c3acd2c379a4580b797b91"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/scopelint/releases/download/v0.1.3/scopelint_0.1.3_linux_amd64.tar.gz"
      sha256 "f16939fb30d5c7adc00bdc6d6753a0e7342f736faa65d4fcafca36f97d6a72d1"
    end
  end

  def install
    bin.install "scopelint"
    man1.install "scopelint.1"
  end
end
