# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zshist < Formula
  desc "Encode(metafy) / decode(unmetafy) .zsh_history file"
  homepage "https://github.com/kyoh86/zshist"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/zshist/releases/download/v0.0.8/zshist_0.0.8_darwin_amd64.tar.gz"
      sha256 "b22c2db861fadcbfa2f90e3c1a4eb6d30359f439a0af0da81bdaaa029257a746"

      def install
        bin.install "zshist"
        man1.install Dir.glob('zshist*.1')
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyoh86/zshist/releases/download/v0.0.8/zshist_0.0.8_darwin_arm64.tar.gz"
      sha256 "bae58b938d71cc70c33cbd1cc61638688b050e6c03888eae5ae68f888528a9b1"

      def install
        bin.install "zshist"
        man1.install Dir.glob('zshist*.1')
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyoh86/zshist/releases/download/v0.0.8/zshist_0.0.8_linux_arm64.tar.gz"
      sha256 "a7eef13712cf0f84228bf02061a7ad870b8f655e10c90e5f206aac50e5ad61ac"

      def install
        bin.install "zshist"
        man1.install Dir.glob('zshist*.1')
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyoh86/zshist/releases/download/v0.0.8/zshist_0.0.8_linux_amd64.tar.gz"
      sha256 "6c51e7a02ad643a795bb261523eb4181a1cc22b2f3e9903d842252b78ba252e9"

      def install
        bin.install "zshist"
        man1.install Dir.glob('zshist*.1')
      end
    end
  end
end
