# This file was generated by GoReleaser. DO NOT EDIT.
class Zshist < Formula
  desc "Encode(metafy) / decode(unmetafy) .zsh_history file"
  homepage "https://github.com/kyoh86/zshist"
  url "https://github.com/kyoh86/zshist/releases/download/v0.0.6/zshist_0.0.6_darwin_amd64.tar.gz"
  version "0.0.6"
  sha256 "4f6be66e583335c43453b391d69b73591f4d95b722e9323638e451b89dc89f18"

  def install
    bin.install "zshist"
    man1.install "zshist.1"
  end
end
